# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IRC3
version:      0.3
version_from: lib/Net/IRC3.pm
installdirs:  site
requires:
    AnyEvent:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
