--- #YAML:1.0
name:                Net-IRC3
version:             0.5
abstract:            An event system independend IRC protocol module
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    AnyEvent:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Robin Redeker <elmex@ta-sa.org>
