#!/usr/bin/perl
use strict;
use Net::IRC3;
$Net::IRC3::Client::DEBUG = 1;

my $c = AnyEvent->condvar;

my $irc = Net::IRC3->new;

my $con = $irc->connect ("irc.plan9.de", 6667);

my ($nick, $user, $real) = qw/BinDepp BinDepp depp/;

# send IRC registration
$con->send_msg (undef, "NICK", undef, $nick);
$con->send_msg (undef, "USER", $real || $nick, $user || $nick, "*", "0");

$con->reg_cb (irc_001 => sub {
   my ($con) = @_;
   $con->event ('welcome'); # emit a self defined event
   1;
});

# display all irc messages for debugging
$con->reg_cb ('irc_*' => sub { warn "DEBUG: " . join ('|', %{$_[1]}) . "\n"; 1; });

# we register now a callback on our self defined event
$con->reg_cb (welcome => sub {
   my ($con) = @_;
   $con->send_msg (undef, "PRIVMSG", "Hi!!!", "elmex");
   1;
});

my $t;
$t = AnyEvent->timer (after => 2, cb => sub {
   $con->disconnect ("Timeout exceeded");
   undef $t;
});

# lets 
$con->reg_cb (
   disconnect => sub {
      warn "Oh, got a disconnect: $_[1], exiting...\n";
      exit 0;
      1;
   }
);

$c->wait;
